version: '2.2'

services:

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory ./data -port 8000"
    image: "amazon/dynamodb-local:latest"
    ports:
    - "8000:8000"
    working_dir: /home/dynamodblocal

    api:
      build:
        context: .
        dockerfile: ./Dockerfile
      command: ["sh", "-c", "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m system"]
      image: api-local:${TESTE_VERSION:-latest}
      restart: always
      volumes:
      - .:/code
      env_file:
      - .env
      ports:
      - "9000:9000"
      - "5678:5678"
