version: '2.2'

services:

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory ./data -port 8000"
    image: "amazon/dynamodb-local:latest"
    ports:
    - "8000:8000"
    working_dir: /home/dynamodblocal
    networks:
    - os-net

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
      # - INSTALL_COMMAND=poetry install --without code-smells,dev
      - INSTALL_COMMAND=poetry install --only main
    # command: ["sh", "-c", "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m system"]
    command: ["sh", "-c", "python -m system"]
    image: teste:${TESTE_VERSION:-latest}
    restart: always
    volumes:
    - .:/code
    env_file:
    - .env
    ports:
    - "9000:9000"
    - "5678:5678"
    environment:
    - ENDPOINT_URL=http://dynamodb-local:8000
    - ENVIRONMENT=local
    - ELASTICSEARCH_HOST=opensearch-node1
    - ELASTICSEARCH_INDEX=short-url
    - ELASTICSEARCH_ACTIVE=true
    networks:
    - os-net
    depends_on:
    - opensearch-node1
    - dynamodb-local


  opensearch-node1:
    image: opensearchproject/opensearch:2.1.0
    container_name: opensearch-node1
    environment:
    - cluster.name=opensearch-cluster
    - node.name=opensearch-node-operations
    - bootstrap.memory_lock=true   # along with the memlock settings below, disables swapping
    - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"   # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    - "DISABLE_INSTALL_DEMO_CONFIG=true"   # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
    - "DISABLE_SECURITY_PLUGIN=true"   # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
    - "discovery.type=single-node"   # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    # volumes:
    # - opensearch-data1:/usr/share/opensearch/data
    ports:
    - 9200:9200
    - 9600:9600   # required for Performance Analyzer
    networks:
    - os-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.1.0
    container_name: opensearch-dashboards
    ports:
    - 5601:5601
    expose:
    - "5601"
    environment:
    - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
    - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"   # disables security dashboards plugin in OpenSearch Dashboards
    networks:
    - os-net

  # opensearch-logstash:
  #   image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
  #   container_name: opensearch-logstash
  #   stdin_open: true
  #   tty: true
  #   command:
  #     - "-e"
  #     - |
  #       input {
  #         stdin {}
  #       }
  #       output {
  #         opensearch {
  #           hosts => ["https://opensearch-node1:9200"]
  #           index => "opensearch-logstash-docker-%{+YYYY.MM.dd}"
  #           user => "admin"
  #           password => "admin"
  #           ssl => true
  #           ssl_certificate_verification => false
  #         }
  #       }

  #   # volumes:
  #   #   - /mnt/c/Users/Gabriel/Documents/meli-challenge/url-shortne/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
  #   #   - /mnt/c/Users/Gabriel/Documents/meli-challenge/url-shortne/logstash/pipeline:/usr/share/logstash/pipeline:ro,z
  #   environment:
  #     - 'LS_JAVA_OPTS=-Xmx256m -Xms256m'
  #     - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
  #   ports:
  #     - "5044:5044"
  #     - "5000:5000/tcp"
  #     - "5000:5000/udp"
  #     - "8080:8080/tcp"
  #   expose:
  #   - "5000"
  #   networks:
  #     - os-net
  #   depends_on:
  #     - opensearch-node1



volumes:
  opensearch-data1:
  db-data:
    name: db-data

networks:
  os-net:
    driver: bridge
