version: '2.2'

services:

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory ./data -port 8000"
    image: "amazon/dynamodb-local:latest"
    ports:
    - "8001:8001"
    working_dir: /home/dynamodblocal
