name: Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Split branch name
      id: split
      env:
        BRANCH_NAME: "${{ github.head_ref }}"
      run: |
        IFS='/' read -ra VALUES <<< "$BRANCH_NAME"
        echo "branch_prefix=${VALUES[0]}" >> $GITHUB_OUTPUT

    - name: Add Label
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GIT_SERVICE_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
          -d '["${{ steps.split.outputs.branch_prefix }}"]'
